# Generated by Django 5.0.2 on 2024-02-14 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('distance_base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('distance_additional_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_multiplier_factor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('waiting_charges', models.DecimalField(decimal_places=2, max_digits=8)),
                ('day_of_week', models.CharField(max_length=11)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pricing_configuration',
            },
        ),
    ]
